### ISSUE TITLE
How does the config work? 

### ISSUE THREAD

**Issue by Jorge-lopz** [MattiDragon/no-magic-milk#1]
I tried using different syntax, like
- minecraft:slowness
- slowness
on blacklist mode, and it doesn't actually change anything.

**Comment by MattiDragon** [comment]
Can you show the whole file? I haven't touched this mod in forever

**Comment by Jorge-lopz** [comment]
Sure
[no_magic_milk.txt](https://github.com/MattiDragon/no-magic-milk/files/9086331/no_magic_milk.txt)

**Comment by MattiDragon** [comment]
Just checked the code. You need to set the filter to the exact same id as the effect has. You need the `minecraft:` and mod prefixes. But you config should work.

I'm not going to be able to fix any problems in the code for a while, so let's hope you messed up somehow.

Did you restart the game after charging? It might fix it

**Comment by Jorge-lopz** [comment]
I'll keep trying
Thanks a lot
